{"uuid": "4525bb6b-0184-4d80-9f74-b1e45bc9cf1c", "children": ["f02de596-76a0-438d-ab65-1bfd2eee4c67"], "befores": [{"name": "precondition", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=111.0.5563.111)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0104DCE3]\n\t(No symbol) [0x00FE39D1]\n\t(No symbol) [0x00EF4DA8]\n\t(No symbol) [0x00EDD0D3]\n\t(No symbol) [0x00F3EA8B]\n\t(No symbol) [0x00F4D093]\n\t(No symbol) [0x00F3ACC6]\n\t(No symbol) [0x00F16F68]\n\t(No symbol) [0x00F180CD]\n\tGetHandleVerifier [0x012C3832+2506274]\n\tGetHandleVerifier [0x012F9794+2727300]\n\tGetHandleVerifier [0x012FE36C+2746716]\n\tGetHandleVerifier [0x010F6690+617600]\n\t(No symbol) [0x00FEC712]\n\t(No symbol) [0x00FF1FF8]\n\t(No symbol) [0x00FF20DB]\n\t(No symbol) [0x00FFC63B]\n\tBaseThreadInitThunk [0x76826BD9+25]\n\tRtlGetFullPathName_UEx [0x77778FD2+1218]\n\tRtlGetFullPathName_UEx [0x77778F9D+1165]\n\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\AFWB70B\\generic\\base_setup.py\", line 71, in precondition\n    self.driver.maximize_window()\n  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in maximize_window\n    self.execute(command, None)\n  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\pycharmprojects\\afwb70\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1679926655321, "stop": 1679926660818}], "start": 1679926655321, "stop": 1679926661146}